module.exports = function () {
    return function () {
        // Quest Factory generates a quest dependent on certain factors.
        // Quests can be generated by other quests. These will run a suitable quest factory at a certain time.
        // Quests can be given by visiting certain places and looking for them.
        // Some quests are permanent fixtures, but will have slight variations. These will be buffs or training.
    };
};
