module.exports = function () {
    "use strict";

    return function () {
        // Quest Factory generates a quest dependent on certain factors.
        // Quests can be generated by other quests. 
        // These will run a suitable quest factory at a certain time.
        // Quests can be given by visiting certain places and looking for them.
        // Some quests are permanent fixtures, but will have slight variations. 
        // These will be buffs or training.
        var generator;

        this.generator = function (value) {
            if (value) {
                generator = value;
            }
            return generator;
        };
        this.generate = function (player, contextName, rewardType, questType) {
            // Player object is passed in.
            // Quests are generated based on skills and quests completed.
            // Check for existing quest of type contextName, rewardType, 
            // questType
            // If none exists, create one through the function assigned.
            return [player, contextName, rewardType, questType];
            // Returns a Quest.
        };
    };
};
